---

- name: DROPBOX Check if direactory already exist
  stat: 
    path: $HOME/.dropbox-dist
  register: dropbox_folder

- name: DROPBOX - download
  shell: cd ~ && wget -O - "https://www.dropbox.com/download?plat=lnx.x86_64" | tar xzf -
  when: not dropbox_folder.stat.exists

- name: DROPBOX - generate desktop file
  template:
    src: "dropbox.desktop.j2"
    dest: "$HOME/.config/autostart/dropbox.desktop"

